/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Robin
 */
import java.awt.CardLayout;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.util.List;

import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

public class Display extends javax.swing.JFrame {
    private Controller controller;
    
    /**
     * Creates new form Display
     */
    public Display() {
        initComponents();
    }
    
    public Display(Controller controller) {
        initComponents();
        this.controller = controller;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tripType = new javax.swing.ButtonGroup();
        jButton5 = new javax.swing.JButton();
        loginPanel = new javax.swing.JPanel();
        OldUserSignIn = new javax.swing.JPanel();
        oldUserUsernameField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        oldUserSignIn = new javax.swing.JButton();
        oldUserPasswordField = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        newUserUsernameField = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        createAccountButton = new javax.swing.JButton();
        newUserPasswordField = new javax.swing.JPasswordField();
        adminPanel = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        adminDeleteTripButton = new javax.swing.JButton();
        adminEditAssignmentButton = new javax.swing.JButton();
        adminViewTripButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        adminTripsTable = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        adminLegsTable = new javax.swing.JTable();
        adminLogoutButton = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        adminLoggedInAsLabel = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        userPanel = new javax.swing.JPanel();
        userSearchFlightButton = new javax.swing.JButton();
        userViewFlightHistoryButton = new javax.swing.JButton();
        userFlightHistoryScroll = new javax.swing.JScrollPane();
        userFlightHistoryTable = new javax.swing.JTable();
        userLogoutButton = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        userLoggedInAsLabel = new javax.swing.JLabel();
        flightSearchPanel = new javax.swing.JPanel();
        searchResultsPanel = new javax.swing.JPanel();
        selectTripButton = new javax.swing.JButton();
        searchResultsScroll = new javax.swing.JScrollPane();
        searchResultsTable = new javax.swing.JTable();
        basicSearchPanel = new javax.swing.JPanel();
        basicSearchButton = new javax.swing.JButton();
        leavingDateField = new javax.swing.JTextField();
        leavingTimeField = new javax.swing.JTextField();
        goingDateField = new javax.swing.JTextField();
        goingTimeField = new javax.swing.JTextField();
        leavingComboBox = new javax.swing.JComboBox();
        goingComboBox = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        oneWayRadio = new javax.swing.JRadioButton();
        roundTripRadio = new javax.swing.JRadioButton();
        plusMinusLeavingCombo = new javax.swing.JComboBox();
        plusMinusGoingCombo = new javax.swing.JComboBox();
        basicSearchLogoutButton = new javax.swing.JButton();
        basicSearchBackButton = new javax.swing.JButton();
        paymentPanel = new javax.swing.JPanel();
        paymentSubmitPanel = new javax.swing.JPanel();
        paymentNameField = new javax.swing.JTextField();
        paymentEmailField = new javax.swing.JTextField();
        paymentStreetField = new javax.swing.JTextField();
        paymentAccountNumField = new javax.swing.JTextField();
        paymentAccountNameField = new javax.swing.JTextField();
        paymentPhoneField = new javax.swing.JTextField();
        paymentStateField = new javax.swing.JTextField();
        paymentZipField = new javax.swing.JTextField();
        paymentSubmitButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        paymenLogoutButton = new javax.swing.JButton();
        paymentBackButton = new javax.swing.JButton();

        jButton5.setText("jButton5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jLabel9.setText("Username");

        jLabel18.setText("Password");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("Sign In");

        oldUserSignIn.setText("Sign In");
        oldUserSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldUserSignInActionPerformed(evt);
            }
        });

        oldUserPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldUserPasswordFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OldUserSignInLayout = new javax.swing.GroupLayout(OldUserSignIn);
        OldUserSignIn.setLayout(OldUserSignInLayout);
        OldUserSignInLayout.setHorizontalGroup(
            OldUserSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OldUserSignInLayout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addGroup(OldUserSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel22)
                    .addComponent(jLabel18)
                    .addComponent(jLabel9)
                    .addComponent(oldUserUsernameField)
                    .addComponent(oldUserSignIn, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(oldUserPasswordField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        OldUserSignInLayout.setVerticalGroup(
            OldUserSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OldUserSignInLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(oldUserUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(oldUserPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(oldUserSignIn)
                .addGap(17, 17, 17))
        );

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("New User");

        jLabel20.setText("Password");

        newUserUsernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newUserUsernameFieldActionPerformed(evt);
            }
        });

        jLabel21.setText("Username");

        createAccountButton.setText("Create Account");
        createAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccountButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OldUserSignIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1))
                .addContainerGap())
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(newUserUsernameField)
                    .addComponent(jLabel19)
                    .addComponent(createAccountButton, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(newUserPasswordField))
                .addContainerGap(324, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(OldUserSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newUserUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addGap(8, 8, 8)
                .addComponent(newUserPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(createAccountButton)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        getContentPane().add(loginPanel, "loginCard");

        jLabel25.setText("Trips:");

        adminDeleteTripButton.setText("Delete");
        adminDeleteTripButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminDeleteTripButtonActionPerformed(evt);
            }
        });

        adminEditAssignmentButton.setText("Edit Assignment");
        adminEditAssignmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminEditAssignmentButtonActionPerformed(evt);
            }
        });

        adminViewTripButton.setText("View");
        adminViewTripButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminViewTripButtonActionPerformed(evt);
            }
        });

        adminTripsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Trip Number", "Airline", "Price", "Departure", "Destination", "Number of Legs"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(adminTripsTable);

        adminLegsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Trip Number", "Leg Number", "Seats Available", "Date", "Assignment"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(adminLegsTable);

        adminLogoutButton.setText("Logout");
        adminLogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminLogoutButtonActionPerformed(evt);
            }
        });

        jLabel26.setText("Logged in as : ");

        jLabel23.setText("Legs:");

        javax.swing.GroupLayout adminPanelLayout = new javax.swing.GroupLayout(adminPanel);
        adminPanel.setLayout(adminPanelLayout);
        adminPanelLayout.setHorizontalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminPanelLayout.createSequentialGroup()
                        .addComponent(adminLoggedInAsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 464, Short.MAX_VALUE)
                        .addComponent(adminLogoutButton))
                    .addGroup(adminPanelLayout.createSequentialGroup()
                        .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(adminPanelLayout.createSequentialGroup()
                                .addGap(397, 397, 397)
                                .addComponent(adminEditAssignmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminPanelLayout.createSequentialGroup()
                                .addComponent(adminViewTripButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(adminDeleteTripButton)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        adminPanelLayout.setVerticalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminLogoutButton)
                    .addComponent(jLabel26)
                    .addComponent(adminLoggedInAsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminDeleteTripButton)
                    .addComponent(adminViewTripButton))
                .addGap(11, 11, 11)
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(adminEditAssignmentButton)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(adminPanel, "adminCard");

        userSearchFlightButton.setText("Search Flights");
        userSearchFlightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userSearchFlightButtonActionPerformed(evt);
            }
        });

        userViewFlightHistoryButton.setText("View Flight History");
        userViewFlightHistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userViewFlightHistoryButtonActionPerformed(evt);
            }
        });

        userFlightHistoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Trip Number", "Airline", "Price", "Departure", "Destination", "Number of Legs"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        userFlightHistoryScroll.setViewportView(userFlightHistoryTable);

        userLogoutButton.setText("Logout");
        userLogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userLogoutButtonActionPerformed(evt);
            }
        });

        jLabel24.setText("Logged in as: ");

        javax.swing.GroupLayout userPanelLayout = new javax.swing.GroupLayout(userPanel);
        userPanel.setLayout(userPanelLayout);
        userPanelLayout.setHorizontalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userPanelLayout.createSequentialGroup()
                        .addComponent(userFlightHistoryScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 134, Short.MAX_VALUE))
                    .addGroup(userPanelLayout.createSequentialGroup()
                        .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(userSearchFlightButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(userViewFlightHistoryButton, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE))
                            .addGroup(userPanelLayout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addGap(18, 18, 18)
                                .addComponent(userLoggedInAsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 310, Short.MAX_VALUE)
                        .addComponent(userLogoutButton)))
                .addContainerGap())
        );
        userPanelLayout.setVerticalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(userLogoutButton))
                    .addGroup(userPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userLoggedInAsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))))
                .addGap(12, 12, 12)
                .addComponent(userSearchFlightButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userViewFlightHistoryButton)
                .addGap(18, 18, 18)
                .addComponent(userFlightHistoryScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        getContentPane().add(userPanel, "userCard");

        searchResultsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Results", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N

        selectTripButton.setText("Select");
        selectTripButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectTripButtonActionPerformed(evt);
            }
        });

        searchResultsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Trip Number", "Airline", "Price", "Departure", "Destination", "Number of Legs"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        searchResultsScroll.setViewportView(searchResultsTable);

        javax.swing.GroupLayout searchResultsPanelLayout = new javax.swing.GroupLayout(searchResultsPanel);
        searchResultsPanel.setLayout(searchResultsPanelLayout);
        searchResultsPanelLayout.setHorizontalGroup(
            searchResultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(searchResultsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchResultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchResultsScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchResultsPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(selectTripButton, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        searchResultsPanelLayout.setVerticalGroup(
            searchResultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchResultsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchResultsScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(selectTripButton)
                .addContainerGap())
        );

        basicSearchPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N

        basicSearchButton.setText("Search");
        basicSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basicSearchButtonActionPerformed(evt);
            }
        });

        leavingComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        goingComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel10.setText("Leaving From:");

        jLabel11.setText("Going To:");

        jLabel12.setText("Date (DD-MMM-YY)");

        jLabel13.setText("+/- days");

        jLabel14.setText("Time HH:MM:SS");

        jLabel15.setText("Date Date (DD-MMM-YY)");

        jLabel16.setText("+/- days");

        jLabel17.setText("Time Time HH:MM:SS");

        tripType.add(oneWayRadio);
        oneWayRadio.setText("One way");
        oneWayRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneWayRadioActionPerformed(evt);
            }
        });

        tripType.add(roundTripRadio);
        roundTripRadio.setText("Round Trip");
        roundTripRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundTripRadioActionPerformed(evt);
            }
        });

        plusMinusLeavingCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        plusMinusGoingCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout basicSearchPanelLayout = new javax.swing.GroupLayout(basicSearchPanel);
        basicSearchPanel.setLayout(basicSearchPanelLayout);
        basicSearchPanelLayout.setHorizontalGroup(
            basicSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basicSearchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(basicSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(basicSearchPanelLayout.createSequentialGroup()
                        .addComponent(oneWayRadio)
                        .addGap(18, 18, 18)
                        .addComponent(roundTripRadio)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, basicSearchPanelLayout.createSequentialGroup()
                        .addGroup(basicSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(goingComboBox, 0, 261, Short.MAX_VALUE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(leavingComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(basicSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(basicSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(basicSearchPanelLayout.createSequentialGroup()
                                .addGroup(basicSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(goingDateField)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel15)
                                    .addComponent(leavingDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(basicSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(basicSearchPanelLayout.createSequentialGroup()
                                        .addGroup(basicSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel16)
                                            .addComponent(plusMinusLeavingCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(25, 25, 25)
                                        .addGroup(basicSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel14)
                                            .addComponent(leavingTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(basicSearchPanelLayout.createSequentialGroup()
                                        .addComponent(plusMinusGoingCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(25, 25, 25)
                                        .addComponent(goingTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
        );
        basicSearchPanelLayout.setVerticalGroup(
            basicSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basicSearchPanelLayout.createSequentialGroup()
                .addGroup(basicSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oneWayRadio)
                    .addComponent(roundTripRadio))
                .addGap(18, 18, 18)
                .addGroup(basicSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(basicSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(leavingComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(leavingDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(leavingTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plusMinusLeavingCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(basicSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(basicSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(goingComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goingDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goingTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plusMinusGoingCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(basicSearchButton))
        );

        basicSearchLogoutButton.setText("Logout");

        basicSearchBackButton.setText("Back");
        basicSearchBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basicSearchBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout flightSearchPanelLayout = new javax.swing.GroupLayout(flightSearchPanel);
        flightSearchPanel.setLayout(flightSearchPanelLayout);
        flightSearchPanelLayout.setHorizontalGroup(
            flightSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(flightSearchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(flightSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(flightSearchPanelLayout.createSequentialGroup()
                        .addComponent(basicSearchBackButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(basicSearchLogoutButton))
                    .addComponent(basicSearchPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchResultsPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        flightSearchPanelLayout.setVerticalGroup(
            flightSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, flightSearchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(flightSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(basicSearchLogoutButton)
                    .addComponent(basicSearchBackButton))
                .addGap(27, 27, 27)
                .addComponent(basicSearchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchResultsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(flightSearchPanel, "flightSearchCard");

        paymentSubmitPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Payment", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N

        paymentNameField.setText("jTextField1");

        paymentEmailField.setText("jTextField2");

        paymentStreetField.setText("jTextField3");

        paymentAccountNumField.setText("jTextField4");

        paymentAccountNameField.setText("jTextField5");

        paymentPhoneField.setText("jTextField6");

        paymentStateField.setText("jTextField13");

        paymentZipField.setText("jTextField14");

        paymentSubmitButton.setText("Submit Payment");

        jLabel1.setText("Name");

        jLabel2.setText("Email");

        jLabel3.setText("Phone");

        jLabel4.setText("Street");

        jLabel5.setText("State");

        jLabel6.setText("Zip");

        jLabel7.setText("Account #");

        jLabel8.setText("Name on Account");

        javax.swing.GroupLayout paymentSubmitPanelLayout = new javax.swing.GroupLayout(paymentSubmitPanel);
        paymentSubmitPanel.setLayout(paymentSubmitPanelLayout);
        paymentSubmitPanelLayout.setHorizontalGroup(
            paymentSubmitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentSubmitPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paymentSubmitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(paymentStreetField, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(paymentAccountNumField)
                    .addComponent(paymentNameField))
                .addGap(18, 18, 18)
                .addGroup(paymentSubmitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paymentSubmitPanelLayout.createSequentialGroup()
                        .addGap(0, 262, Short.MAX_VALUE)
                        .addComponent(paymentSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))
                    .addGroup(paymentSubmitPanelLayout.createSequentialGroup()
                        .addGroup(paymentSubmitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paymentSubmitPanelLayout.createSequentialGroup()
                                .addGroup(paymentSubmitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(paymentEmailField)
                                    .addComponent(paymentStateField, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                    .addComponent(paymentAccountNameField))
                                .addGap(18, 18, 18)
                                .addGroup(paymentSubmitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(paymentPhoneField)
                                    .addComponent(paymentZipField, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)))
                            .addComponent(jLabel8))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        paymentSubmitPanelLayout.setVerticalGroup(
            paymentSubmitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentSubmitPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(paymentSubmitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paymentSubmitPanelLayout.createSequentialGroup()
                        .addComponent(paymentSubmitButton)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paymentSubmitPanelLayout.createSequentialGroup()
                        .addGroup(paymentSubmitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(paymentSubmitPanelLayout.createSequentialGroup()
                                .addGroup(paymentSubmitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(paymentSubmitPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(paymentEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(paymentStateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(paymentSubmitPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(paymentPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(paymentZipField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8)
                                .addGap(5, 5, 5)
                                .addComponent(paymentAccountNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(paymentSubmitPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(paymentNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(paymentStreetField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(paymentAccountNumField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(63, 63, 63))))
        );

        paymenLogoutButton.setText("Logout");

        paymentBackButton.setText("Back");

        javax.swing.GroupLayout paymentPanelLayout = new javax.swing.GroupLayout(paymentPanel);
        paymentPanel.setLayout(paymentPanelLayout);
        paymentPanelLayout.setHorizontalGroup(
            paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paymentPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(paymentBackButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paymenLogoutButton)
                .addContainerGap())
            .addGroup(paymentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paymentSubmitPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        paymentPanelLayout.setVerticalGroup(
            paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paymenLogoutButton)
                    .addComponent(paymentBackButton))
                .addGap(114, 114, 114)
                .addComponent(paymentSubmitPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        getContentPane().add(paymentPanel, "paymentCard");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectTripButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectTripButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectTripButtonActionPerformed

    private void basicSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basicSearchButtonActionPerformed
        System.out.println((String)leavingComboBox.getSelectedItem());
        System.out.println((String)goingComboBox.getSelectedItem());
        
        String leavingCode = (String)leavingComboBox.getSelectedItem();
        String goingCode = (String)goingComboBox.getSelectedItem();
        String leavingDate = leavingDateField.getText();        
        String leavingPlusMinus = (String)plusMinusLeavingCombo.getSelectedItem();
        
        String goingPlusMinus = "";
        String goingDate = "";
        if(controller.getTripType() == TripType.ROUND_TRIP)
        {
            goingPlusMinus = (String)plusMinusGoingCombo.getSelectedItem();
            goingDate = goingDateField.getText();
        }
        
        //controller.fillSearchResultsTable(leavingCode, goingCode, leavingDate, goingDate, leavingPlusMinus, goingPlusMinus);
    }//GEN-LAST:event_basicSearchButtonActionPerformed

    private void oneWayRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneWayRadioActionPerformed
        // TODO add your handling code here:
        controller.setTripType(TripType.ONE_WAY);
        goingDateField.setEditable(false);
            goingTimeField.setEditable(false);
            plusMinusGoingCombo.setEditable(false);
    }//GEN-LAST:event_oneWayRadioActionPerformed

    private void createAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountButtonActionPerformed
        // TODO add your handling code here:
        String username = "";
        String password = "";

        username = newUserUsernameField.getText();
        password = new String(newUserPasswordField.getPassword());
        boolean addSuccess = false;
        try
        {
            addSuccess = controller.addUser(username, password);
        }
        catch (SQLException e)
        {
            System.out.println(e.getMessage());
        }
        
        if(addSuccess)
        {
            JOptionPane.showMessageDialog(this, "Welcome: " + username);
            CardLayout cl = (CardLayout) this.getContentPane().getLayout();
            userLoggedInAsLabel.setText(username);
            cl.show(this.getContentPane(), "userCard");
        }
        else
        {
            JOptionPane.showMessageDialog(this, "username taken");
        }
        
        newUserUsernameField.setText("");
        newUserPasswordField.setText("");
    }//GEN-LAST:event_createAccountButtonActionPerformed

    private void oldUserSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldUserSignInActionPerformed
        // TODO add your handling code here:
        String username = "";
        String password = "";

        username = oldUserUsernameField.getText();
        password = new String(oldUserPasswordField.getPassword());
        
        System.out.println("username: " + username);
        System.out.println("passwrod: " + password);
        
        boolean validated = false;        
        validated = controller.validateUser(username, password);
        System.out.println("in validated: " + validated);
        if(validated) 
        {            
            //System.out.print("validated");
            //change cards
            //System.out.println()
            CardLayout cl = (CardLayout) this.getContentPane().getLayout();
            
            //determine user status
            if(controller.getUserAccess().equals(controller.getAdmin()))
            {
                 adminLoggedInAsLabel.setText(username);
                 controller.fillAdminTripTable();                 
                 
                 cl.show(this.getContentPane(), "adminCard");
            }
            else if(controller.getUserAccess().equals(controller.getRestricted()))
            {
                userLoggedInAsLabel.setText(username);
                cl.show(this.getContentPane(), "userCard");
                controller.setLoggedInUser(username, password);
            }
            else
            {
                System.out.print("invalid access level");
            }           
        }
        else
        {
           JOptionPane.showMessageDialog(this, "invalid username password combo");
        }        
        
        oldUserUsernameField.setText("");
        oldUserPasswordField.setText("");
    }//GEN-LAST:event_oldUserSignInActionPerformed

    private void adminDeleteTripButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminDeleteTripButtonActionPerformed
        
        //make sure really want to delete
         Object[] options = {"Yes", "No"};
        int n = JOptionPane.showOptionDialog(
            null,
            "Are you sure you would like to remove this trip?",
            "Remove Item Confirmation",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE,
            null,           //do not use a custom Icon
            options,        //the titles of buttons
            options[1]      //default to keeping the row
        );
        
        if(n!=JOptionPane.YES_OPTION)
        {
            return;
        }
        
        int index = this.adminTripsTable.getSelectedRow();
        //System.out.println("selected row: " + index);       
        
        javax.swing.table.DefaultTableModel inventoryModel = (javax.swing.table.DefaultTableModel)adminTripsTable.getModel();
        Object tripNum = inventoryModel.getValueAt(index, 0);
        //System.out.println("trip num: " + (String)tripNum);      
        
        //clear from database
        if(controller.removeTrip((String) tripNum))
        {
            // clear all the row
            inventoryModel.removeRow(index);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Trip " + tripNum + " could not be removed");
        }
    }//GEN-LAST:event_adminDeleteTripButtonActionPerformed

    private void newUserUsernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newUserUsernameFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_newUserUsernameFieldActionPerformed

    private void adminLogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminLogoutButtonActionPerformed
        //back to homescreen
        CardLayout cl = (CardLayout) this.getContentPane().getLayout();
        cl.show(this.getContentPane(), "loginCard");
        
        //clear tables        
    }//GEN-LAST:event_adminLogoutButtonActionPerformed

    private void oldUserPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldUserPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oldUserPasswordFieldActionPerformed

    private void adminViewTripButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminViewTripButtonActionPerformed
        //fill leg table w legs corresp to trip
        int index = this.adminTripsTable.getSelectedRow();
        //System.out.println("selected row: " + index);       
        if(index < 0)
        {
            return;
        }
        
        javax.swing.table.DefaultTableModel adminTableModel = (javax.swing.table.DefaultTableModel)adminTripsTable.getModel();
        Object tripNum = adminTableModel.getValueAt(index, 0);
        
        controller.fillAdminLegTable((String)tripNum);        
    }//GEN-LAST:event_adminViewTripButtonActionPerformed

    private void adminEditAssignmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminEditAssignmentButtonActionPerformed
        //fill leg table w legs corresp to trip
        int index = this.adminLegsTable.getSelectedRow();
        //System.out.println("selected row: " + index);       
        if(index < 0)
        {
            return;
        }
        
        javax.swing.table.DefaultTableModel legTableModel = (javax.swing.table.DefaultTableModel)adminLegsTable.getModel();
        Object tripNum = legTableModel.getValueAt(index, 0);
        Object legNum = legTableModel.getValueAt(index, 1);
        Object currentPlane = legTableModel.getValueAt(index, 4);
        
        List<String> planes = controller.getPlaneOptions();
        String options[] = planes.toArray(new String[planes.size()]);
        
        String s = (String)JOptionPane.showInputDialog(
                    this,
                    "Select different plane: ",
                    "Customized Dialog",
                    JOptionPane.PLAIN_MESSAGE,
                    null,
                    options,
                    "");        
        
        if(s.equals((String)currentPlane))
        {
            return;
        }
        else
        {
            //change plane & refresh table
            controller.changePlane((String)tripNum, (String)legNum, s);            
            controller.fillAdminLegTable((String)tripNum);
        }
        
    }//GEN-LAST:event_adminEditAssignmentButtonActionPerformed

    private void userViewFlightHistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userViewFlightHistoryButtonActionPerformed
        controller.fillUserFlightHistoryPanel();        
    }//GEN-LAST:event_userViewFlightHistoryButtonActionPerformed

    private void userLogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userLogoutButtonActionPerformed
        CardLayout cl = (CardLayout) this.getContentPane().getLayout();
        cl.show(this.getContentPane(), "loginCard");
    }//GEN-LAST:event_userLogoutButtonActionPerformed

    private void userSearchFlightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userSearchFlightButtonActionPerformed
        CardLayout cl = (CardLayout) this.getContentPane().getLayout();
        cl.show(this.getContentPane(), "flightSearchCard");    
        
        //*******populate combo boxes
        controller.populateSearchComboBoxes();
        setPlusMinusCombos();
        
        if(controller.getTripType() == TripType.ONE_WAY)
        {
            goingDateField.setEditable(false);
            goingTimeField.setEditable(false);
            plusMinusGoingCombo.setEditable(false);
        }
    }//GEN-LAST:event_userSearchFlightButtonActionPerformed

    private void basicSearchBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basicSearchBackButtonActionPerformed
        CardLayout cl = (CardLayout) this.getContentPane().getLayout();
        cl.show(this.getContentPane(), "userCard"); 
    }//GEN-LAST:event_basicSearchBackButtonActionPerformed

    private void roundTripRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundTripRadioActionPerformed
        controller.setTripType(TripType.ROUND_TRIP);
        goingDateField.setEditable(true);
            goingTimeField.setEditable(true);
            plusMinusGoingCombo.setEditable(true);
    }//GEN-LAST:event_roundTripRadioActionPerformed

    public void displayAdminTrips(List<Trip> trips)
    {
        javax.swing.table.DefaultTableModel adminTripsModel =
            (javax.swing.table.DefaultTableModel)this.adminTripsTable.getModel();
        // clear all the rows
        for(int i = adminTripsModel.getRowCount()-1; i >= 0; i--) {
            adminTripsModel.removeRow(i);
        }
        
        //add back rows: trip_number, airline, price, departure, destination, number_of_legs
        for(int i = 0; i < trips.size(); i++) {
            adminTripsModel.addRow(new Object[] {
                trips.get(i).getTrip_number(),
                trips.get(i).getAirline(),
                trips.get(i).getPrice(),
                trips.get(i).getDeparture(),
                trips.get(i).getDestination(),
                trips.get(i).getNumber_of_legs()
            });
        }
    }
    
    public void displayAdminLegs(List<Leg> legs)
    {
         javax.swing.table.DefaultTableModel adminLegsModel =
            (javax.swing.table.DefaultTableModel)this.adminLegsTable.getModel();
        // clear all the rows
        for(int i = adminLegsModel.getRowCount()-1; i >= 0; i--) {
            adminLegsModel.removeRow(i);
        }
        
        System.out.println("legssize: " + legs.size());
        
        //add back rows: trip_number, airline, price, departure, destination, number_of_legs
        for(int i = 0; i < legs.size(); i++) {
            adminLegsModel.addRow(new Object[] {
                legs.get(i).getTrip_number(),
                legs.get(i).getLeg_number(),
                legs.get(i).getSeats_available(),
                legs.get(i).getFlight_date(),
                legs.get(i).getAssignment(),        
            });
        }
    }
    
    public void displayFlightHistory(List<Trip> trips)
    {
         javax.swing.table.DefaultTableModel flightHistoryModel =
            (javax.swing.table.DefaultTableModel)this.userFlightHistoryTable.getModel();
        // clear all the rows
        for(int i = flightHistoryModel.getRowCount()-1; i >= 0; i--) {
            flightHistoryModel.removeRow(i);
        }
        
        //add back rows: trip_number, airline, price, departure, destination, number_of_legs
        for(int i = 0; i < trips.size(); i++) {
            flightHistoryModel.addRow(new Object[] {
                trips.get(i).getTrip_number(),
                trips.get(i).getAirline(),
                trips.get(i).getPrice(),
                trips.get(i).getDeparture(),
                trips.get(i).getDestination(),
                trips.get(i).getNumber_of_legs()
            });
        }
    }
    
    public void setLeavingGoingCombos(String[] leaving, String[] going)
    {
        leavingComboBox.removeAllItems();
        goingComboBox.removeAllItems();
        
        for(String l: leaving)
        {
            leavingComboBox.addItem(l);
        }
        for(String g: going)
        {
            goingComboBox.addItem(g);
        }
    }
    
    public void setPlusMinusCombos()
    {
        String[] days = {"", "1", "2"};
        plusMinusLeavingCombo.removeAllItems();
        plusMinusGoingCombo.removeAllItems();
        
        for(String d: days)
        {
            plusMinusLeavingCombo.addItem(d);
            plusMinusGoingCombo.addItem(d);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Display().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel OldUserSignIn;
    private javax.swing.JButton adminDeleteTripButton;
    private javax.swing.JButton adminEditAssignmentButton;
    private javax.swing.JTable adminLegsTable;
    private javax.swing.JLabel adminLoggedInAsLabel;
    private javax.swing.JButton adminLogoutButton;
    private javax.swing.JPanel adminPanel;
    private javax.swing.JTable adminTripsTable;
    private javax.swing.JButton adminViewTripButton;
    private javax.swing.JButton basicSearchBackButton;
    private javax.swing.JButton basicSearchButton;
    private javax.swing.JButton basicSearchLogoutButton;
    private javax.swing.JPanel basicSearchPanel;
    private javax.swing.JButton createAccountButton;
    private javax.swing.JPanel flightSearchPanel;
    private javax.swing.JComboBox goingComboBox;
    private javax.swing.JTextField goingDateField;
    private javax.swing.JTextField goingTimeField;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox leavingComboBox;
    private javax.swing.JTextField leavingDateField;
    private javax.swing.JTextField leavingTimeField;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPasswordField newUserPasswordField;
    private javax.swing.JTextField newUserUsernameField;
    private javax.swing.JPasswordField oldUserPasswordField;
    private javax.swing.JButton oldUserSignIn;
    private javax.swing.JTextField oldUserUsernameField;
    private javax.swing.JRadioButton oneWayRadio;
    private javax.swing.JButton paymenLogoutButton;
    private javax.swing.JTextField paymentAccountNameField;
    private javax.swing.JTextField paymentAccountNumField;
    private javax.swing.JButton paymentBackButton;
    private javax.swing.JTextField paymentEmailField;
    private javax.swing.JTextField paymentNameField;
    private javax.swing.JPanel paymentPanel;
    private javax.swing.JTextField paymentPhoneField;
    private javax.swing.JTextField paymentStateField;
    private javax.swing.JTextField paymentStreetField;
    private javax.swing.JButton paymentSubmitButton;
    private javax.swing.JPanel paymentSubmitPanel;
    private javax.swing.JTextField paymentZipField;
    private javax.swing.JComboBox plusMinusGoingCombo;
    private javax.swing.JComboBox plusMinusLeavingCombo;
    private javax.swing.JRadioButton roundTripRadio;
    private javax.swing.JPanel searchResultsPanel;
    private javax.swing.JScrollPane searchResultsScroll;
    private javax.swing.JTable searchResultsTable;
    private javax.swing.JButton selectTripButton;
    private javax.swing.ButtonGroup tripType;
    private javax.swing.JScrollPane userFlightHistoryScroll;
    private javax.swing.JTable userFlightHistoryTable;
    private javax.swing.JLabel userLoggedInAsLabel;
    private javax.swing.JButton userLogoutButton;
    private javax.swing.JPanel userPanel;
    private javax.swing.JButton userSearchFlightButton;
    private javax.swing.JButton userViewFlightHistoryButton;
    // End of variables declaration//GEN-END:variables
}
